config/routes.rb
Rails.application.routes.draw do
  get '/aquisition_pokemon', to: 'pokemon#new_aquisition'
  post "/buy_pokemon", to: "pokemon#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  def new_aquisition
    @pokemons_data = fetch_pokemons_info
  end
  
  def create
    
    binding.pry
    Pokemon.new(pokemon_params)
  end

  def sell_pokemon

  end

  private

  def fetch_pokemons_info
    #pega as infos: name, type, experience_quotation da API e retorna em um array de hash fprmatado
    response = Faraday.get("https://pokeapi.co/api/v2/pokemon")
    data = JSON.parse(response.body)["results"]
    poke_names = data.map{|pokemon| pokemon["name"]}

    pokemon_data(poke_names)
  end

  def  pokemon_data(poke_names)
    values = poke_names.map do |name|
      
      data = fetch_pokemon_data(name)

      photo = data["sprites"]["other"]["dream_world"]["front_default"]
      type = data["types"].map{|info| info["type"]["name"]}
      experience = data["base_experience"]

      { name: name, photo: photo, type: type, base_experience: experience, price: experience_quotation(data["base_experience"]).ceil(2) }
    end
  end

  def btc_quotation
    response = Faraday.get("https://www.mercadobitcoin.net/api/BTC/ticker/")
    JSON.parse(response.body)["ticker"]["last"].to_f
  end  

  def experience_quotation(experience)
    btc_quotas = experience * 0.00000001
    final_price = btc_quotas * btc_quotation
  end

  def fetch_pokemon_data(name)
    response = Faraday.get("https://pokeapi.co/api/v2/pokemon/#{name}")
    JSON.parse(response.body)
  end

  def pokemon_params
    params
      .require(:pokemon)
      .permit(
        :name,
        :price,
        :type,
        :xp,
        :photo,
        :status
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokecoins</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemon/new_aquisition.html.erb
 
<div class="row ">
  <%= @pokemons_data.each do |pokemon| %>
    <div class="col-md-3 poke-card">
      <div class="card ">
        <%= image_tag pokemon[:photo], class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= pokemon[:name].capitalize %>
            <% pokemon[:type].each do |type|%>
            <span class="badge bg-primary"><%= type %></span>
            <% end %>
          </h5>
          <p>Experience: <%= pokemon[:base_experience]%> | Price: R$ <%= pokemon[:price] %></p>
        </div>
        <div class="card-footer">
          <%=  button_to  "Buy Now", buy_pokemon_path( name: pokemon[:name], xp: pokemon[:base_experience], price: pokemon[:price], photo: pokemon[:photo], type: "#{pokemon[:type]}", status:"disponivel" ),  class: "btn btn-primary", method: "post" %>
        </div>
      </div>
    </div>
  <% end %>
</div>


